[package]
name = "day4"
version = "0.1.0"
edition = "2021"

[dependencies]
grid.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day4-bench"
path = "bench/bench.rs"
harness = false
