[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day3-bench"
path = "bench/bench.rs"
harness = false
