[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true
nom_locate.workspace = true
glam.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day15-bench"
path = "bench/bench.rs"
harness = false
