[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true
nom_locate.workspace = true
glam.workspace = true
pathfinding.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day16-bench"
path = "bench/bench.rs"
harness = false
